services:
  hugo:
    build:
      context: .
      args:
        UID: 1000
        GID: 1000
    # image: hugo-dart-sass:latest
    container_name: hugo_container
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: ["hugo", "serve", "--bind", "0.0.0.0", "--buildDrafts"]
    ports:
      - "1313:1313"
